### ISSUE TITLE
Screenshot?  Have you seen the Wordle mock-up in the eCookbook / Demo Programs?

### ISSUE THREAD

**Issue by PySimpleGUI** [krystianpietryka/Wordle_Assistant#2]
Hi there!

You've got a GUI, something that most Python programs don't.  I'm sure visitors would love to see what you've created! (I know I would).

Not long ago I released a WORDLE front-end.  It's missing the integration with a dictionary.  Maybe you could use some of it?  I'm not sure of exactly what you're code does, so maybe you've already done what I posted.

https://pysimplegui.trinket.io/demo-programs#/games/wordle

It's exciting to see people making games and puzzles using  PySimpleGUI.  Thanks for posting your program!

![image](https://user-images.githubusercontent.com/46163555/158965490-53cb9e2f-0ed3-4e85-a3cb-39153f6a6178.png)

**Comment by krystianpietryka** [comment]
Hi!

I am planning many additions to my program, and I will definitely get inspired by your way better Wordle front-end GUI :D (with credit given of course). 

Thank you for the suggestion!

**Comment by PySimpleGUI** [comment]
> Thank you for the suggestion!

You're more than welcome.  Thanks for building programs using PySimpleGUI.

![image](https://user-images.githubusercontent.com/46163555/158976133-a9e5058e-5cfb-4e42-bc67-50ec29c548db.png)

My front end was just me screwing around trying to duplicate the look and feel of the online interface.  I didn't put much into it in terms of checking for the words/letter, so you'll want to double-check my code for sure!  These are always fun little challenges and I learn something new every time I do one.

It's always a thrill to see what people are making... the creativity is incredible.  I particularly like beginners.  I didn't see your game of life until just now.  You're quite a prolific developer.  I've always thought that programming is the best way to learn to program.  Keep building... **you're definitely on the right path**.
